### ISSUE TITLE
DSRC通信

### ISSUE THREAD

**Issue by Xuezhenggdut** [cqu-bdsc/Collision-Warning-System#8]
RSU和OBU之间的DSRC通信不需要其他设置吗？APPpingOBU没问题，APPpingRSU出现问题，OBUpingRSU也ping不通。

**Comment by Xuezhenggdut** [comment]
OBU TWO IP
![QQ截图20191126203857](https://user-images.githubusercontent.com/46556712/69634271-dac48700-108c-11ea-9abf-f8dffd0da317.png)
RSU IP
![QQ截图20191126203913](https://user-images.githubusercontent.com/46556712/69634303-e44def00-108c-11ea-8658-2dd2b6bf113f.png)
Pad2 ping OBU TWO
![QQ截图20191126204030](https://user-images.githubusercontent.com/46556712/69634366-00ea2700-108d-11ea-8905-a1193e413352.png)
![QQ截图20191126204124](https://user-images.githubusercontent.com/46556712/69634431-21b27c80-108d-11ea-92ff-c5a407827f72.png)
OBU TWO bsm-shell
![QQ截图20191126204237](https://user-images.githubusercontent.com/46556712/69634502-4b6ba380-108d-11ea-9d78-7ad472a73f97.png)
RSU bsm-shell
![QQ截图20191126204305](https://user-images.githubusercontent.com/46556712/69634524-5cb4b000-108d-11ea-85c0-4e72d4c2b5f8.png)
OBU ping RSU failed
![QQ截图20191126204341](https://user-images.githubusercontent.com/46556712/69634557-72c27080-108d-11ea-9f41-d6165f6aaeb5.png)

**Comment by FuchengZheng** [comment]
您好 我也出现类似问题 ping 不通 RSU和OBU 之间的DCRC通信。
请问你解决问题了吗？
联系方式：18206660096

**Comment by Xuezhenggdut** [comment]
ping不通的，不能直接在终端ping。我qq634190442，可以交流一下，最近也在搭建碰撞预警系统。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FuchengZheng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月7日(星期六) 晚上9:15
收件人:&nbsp;"cqu-bdsc/Collision-Warning-System"<Collision-Warning-System@noreply.github.com&gt;;
抄送:&nbsp;"xuezhenggdut"<634190442@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cqu-bdsc/Collision-Warning-System] DSRC通信 (#8)




您好 我也出现类似问题 ping 不通 RSU和OBU 之间的DCRC通信。
 请问你解决问题了吗？
 联系方式：18206660096
